### ISSUE TITLE
Reading, recording and editing FA

### ISSUE THREAD

**Issue by ramnaq** [ramnasidharta/midena#1]
- [x] Create class `FiniteAutomata`
- [x] `export_to()`
- [x] `import_from()`
- [x] `UI support (editing)`

**Comment by ramnaq** [comment]
Recording (`export_to()`) was implemented in the branch `finite-automata-ui`. Since reading is already implemented too (`import_from()`), in the branch `dev` (fa935ec), I recommend to continue implementing UI support in the branch `finite-automata-ui`.

**Comment by diogojs** [comment]
Implemented in finite-automata-ui
