### ISSUE TITLE
Convertion from DFA to RG

### ISSUE THREAD

**Issue by ramnaq** [ramnasidharta/midena#3]

**Comment by ramnaq** [comment]
The class `RegularGrammar` was not considering symbols being strings longer than one. Converting Finite Automata to a Regular Grammar made me think that a symbol of a grammar could be represented as `"Q1"` ou `"Q_1"`, for example (equivalent to a `"q1"` state of an Automata). That's why I commented the check `isRegular()` when instantiating the type `RegularGrammar`. This originates a new issue: to implement a type `Token`, which represents a token of a grammar production. For example: `Q_1 -> 0 | 1 | 0Q_2`, `Q_1` would be of type `Token`.

Open for some suggestion on that.

**Comment by diogojs** [comment]
why am I assigned to this issue?

**Comment by ramnaq** [comment]
> The class `RegularGrammar` was not considering symbols being strings longer than one. Converting Finite Automata to a Regular Grammar made me think that a symbol of a grammar could be represented as `"Q1"` ou `"Q_1"`, for example (equivalent to a `"q1"` state of an Automata). That's why I commented the check `isRegular()` when instantiating the type `RegularGrammar`. This originates a new issue: to implement a type `Token`, which represents a token of a grammar production. For example: `Q_1 -> 0 | 1 | 0Q_2`, `Q_1` would be of type `Token`.
> 
> Open for some suggestion on that.

Resolved

**Comment by ramnaq** [comment]
> why am I assigned to this issue?

Oh, the meaning of this assignment is that you're the reviewer, since the card is in the list "Review" in the project board.
