### ISSUE TITLE
Implement Regular Grammars (read, write, edit, convert to NFA)

### ISSUE THREAD

**Issue by ramnaq** [ramnasidharta/midena#5]
- [x] Create class `Grammar`
- [x] `export_to()`
- [x] `import_from()`
- [x] `UI support (editing)`

**Comment by ramnasidharta** [comment]
- [ ] Create class `Grammar`
- [ ] `export_to()`
- [ ] `import_from()`
- [ ] `to_NFA()`
- [ ] `UI support (editing)`

**Comment by ramnaq** [comment]
The methods described above were implemented as functions (`exportGrammar`, `importGrammar`), in the module `models/FileUtil.py`.
